# Generated by Django 2.1 on 2019-03-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_img', models.ImageField(upload_to='face/', verbose_name='アップロード先')),
                ('face_name', models.CharField(blank=True, max_length=20, verbose_name='画像タイトル')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
        ),
        migrations.CreateModel(
            name='SimplePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_img', models.ImageField(upload_to='images/')),
                ('simple_name', models.CharField(max_length=255, verbose_name='画像の名前')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolnum', models.CharField(max_length=5, unique=True, verbose_name='学籍番号')),
                ('user_name', models.CharField(max_length=20, verbose_name='名前')),
                ('password', models.CharField(max_length=6, verbose_name='パスワード')),
                ('free_text', models.CharField(blank=True, max_length=255, verbose_name='フリーテキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
